[package]
name = "simple_win"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cappy3ds_render = { path = "../cappy3ds_render" }
winit = "0.28"
env_logger = "0.10"
log = "0.4"